DROP TABLE EMPLOYEE;
DROP TABLE DEPARTMENT;

CREATE TABLE DEPARTMENT
(
    DEP_ID          INT NOT NULL AUTO_INCREMENT,
    DEPARTMENT_NAME VARCHAR(30),
    MANAGER_NAME VARCHAR(30),
    PRIMARY KEY (`DEP_ID`)
);

CREATE TABLE EMPLOYEE
(
    EMP_ID          INT(11) NOT NULL AUTO_INCREMENT,
    DEP_ID	INT(11) NOT NULL,
    FIRSTNAME   VARCHAR(30),
    LASTNAME    VARCHAR(30),
    TELEPHONE   VARCHAR(15),
    EMAIL       VARCHAR(30),
    CREATED     TIMESTAMP DEFAULT NOW(),
    FOREIGN KEY (DEP_ID) 
        REFERENCES DEPARTMENT(DEP_ID)
        ON DELETE CASCADE,
    PRIMARY KEY (`EMP_ID`)
);
